apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: angular
spec:
  selector:
    matchLabels:
      app: angular
  #replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      -   name: angular
          image: app-crud:frontendv1
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 8080
          # The port that the container is running on in the cluster
